receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: []   # adicione logging/otlp se quiser enviar traces p/ outro destino